INSERT INTO Videos(CourseID, VideoTitle, VideoDescription, OrderInCourse, VideoType, YTVideoID, YTUseDescription)
VALUES
(4, 'How It''s Made - Swords', 'This video teaches you how swords are manufactured.', 1, 0, 'uPm3wHJdyGs', 0),
(4, 'How It''s Made - Parachutes', 'This video teaches you how parachutes are manufactured.', 2,0,'7TfxLzwtGHE', 0),
(4, 'How It''s Made - Seatbelts', NULL, 3, 0, 'Wqbqd8LC5UQ', 1),
(5, 'Video Title', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et tortor consequat id porta nibh venenatis cras sed. Vel facilisis volutpat est velit egestas dui id ornare.', 1, 0, 'XD08Dg4JxFM', 0),
(5, 'Video Title', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et tortor consequat id porta nibh venenatis cras sed. Vel facilisis volutpat est velit egestas dui id ornare.', 2, 0, 'rP0E8E20HQ4', 0),
(5, 'Video Title', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et tortor consequat id porta nibh venenatis cras sed. Vel facilisis volutpat est velit egestas dui id ornare.', 3, 0, '_yt5VjSn8l0', 0),
(5, 'Video Title', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et tortor consequat id porta nibh venenatis cras sed. Vel facilisis volutpat est velit egestas dui id ornare.', 4, 0, 'XB7TsvBQUMQ', 0),
(5, 'Video Title', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et tortor consequat id porta nibh venenatis cras sed. Vel facilisis volutpat est velit egestas dui id ornare.', 5, 0, 'm_z9mTpgdxY', 0),
(5, 'Video Title', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et tortor consequat id porta nibh venenatis cras sed. Vel facilisis volutpat est velit egestas dui id ornare.', 6, 0, 'lwU2ficlHrM', 0),
(5, 'Video Title', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et tortor consequat id porta nibh venenatis cras sed. Vel facilisis volutpat est velit egestas dui id ornare.', 7, 0, 'ku9ACY6lzww', 0),
(5, 'Video Title', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et tortor consequat id porta nibh venenatis cras sed. Vel facilisis volutpat est velit egestas dui id ornare.', 8, 0, 'N1zglmNQ8Tk', 0),
(5, 'Video Title', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et tortor consequat id porta nibh venenatis cras sed. Vel facilisis volutpat est velit egestas dui id ornare.', 9, 0, 'XD08Dg4JxFM', 0),
(5, 'Video Title', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et tortor consequat id porta nibh venenatis cras sed. Vel facilisis volutpat est velit egestas dui id ornare.', 10, 0, 'w7E1rVBt9K4', 0),
(5, 'Video Title', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et tortor consequat id porta nibh venenatis cras sed. Vel facilisis volutpat est velit egestas dui id ornare.', 11, 0, 'bIOOT_gIcmg', 0),
(5, 'Video Title', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et tortor consequat id porta nibh venenatis cras sed. Vel facilisis volutpat est velit egestas dui id ornare.', 12, 0, '4jTWgAqOJSA', 0),
(6, 'Nonexistent Video', 'This video contains a broken link', 1, 0, 'lajkjjjkjkj', 0);
